<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:dateTimeObj="urn:xsltExtension-DateTime">
	<xsl:output omit-xml-declaration="yes" indent="no" method="text" encoding="UTF-8"/>
	<xsl:template match="/">
-- =============================================
-- This stored procedure is generated by BuildProject <xsl:value-of select="entity/@BuildProject"/>, 
-- a freeware develop by bibi.
-- Template: DotNetNuke module EditForm.xslt 17/10/2006
-- Author:	<xsl:value-of select="entity/@author"/>
-- Create date:	<xsl:value-of select="dateTimeObj:GetDateTime('dd/MM/yyyy HH:mm')" />
-- Description:	
-- Revise History:	
-- =============================================

Imports System
Imports System.Web
Imports System.Web.UI
Imports System.Web.UI.WebControls

Namespace DotNetNuke.Modules.<xsl:value-of select="entity/@tableName"/>

    Public MustInherit Class <xsl:value-of select="entity/@tableName"/>_Edit
        Inherits Entities.Modules.PortalModuleBase

#Region "Controls"
        Protected WithEvents cmdUpdate As System.Web.UI.WebControls.LinkButton
        Protected WithEvents cmdCancel As System.Web.UI.WebControls.LinkButton
        Protected WithEvents cmdDelete As System.Web.UI.WebControls.LinkButton
#End Region

#Region "Private Members"
<xsl:apply-templates select="entity" mode="Protected WithEvents"/>
				if(isIdentity)
				{
					sbBody.Append("\tProtected WithEvents " + col.ColumnName + " As System.Web.UI.WebControls.TextBox" + nl);
					continue;
				}
				
				if(isReference)
				{
					sbBody.Append("\tProtected WithEvents " + col.ColumnName + " As System.Web.UI.WebControls.DropDownList" + nl);
					continue;
				}

				sbBody.Append("\tProtected WithEvents " + col.ColumnName + "Label As System.Web.UI.WebControls.Literal" + nl);
				switch (col.DataType.ToLower()) 
				{
					case "date":
					case "datetime":
						sbBody.Append("\tProtected WithEvents " + col.ColumnName + " As Infragistics.WebUI.WebSchedule.WebDateChooser" + nl);
						break;
					case "text":
					case "ntext":
						sbBody.Append("\tProtected WithEvents " + col.ColumnName + " As System.Web.UI.WebControls.TextBox" + nl);
						break;
					case "char":
					case "nchar":
					case "nvarchar":
					case "nvarchar2":
					case "varchar":
					case "varchar2":
						sbBody.Append("\tProtected WithEvents " + col.ColumnName + " As System.Web.UI.WebControls.TextBox" + nl);
						break;
					case "decimal":
					case "float":
					case "numeric":
					case "real":
						sbBody.Append("\tProtected WithEvents " + col.ColumnName + " As System.Web.UI.WebControls.TextBox" + nl);
						break;
					case "int":
					case "number":
					case "integer":
					case "smallint":
					case "tinyint":
						sbBody.Append("\tProtected WithEvents " + col.ColumnName + " As System.Web.UI.WebControls.TextBox" + nl);
						break;
					case "money":
					case "smallmoney":
						sbBody.Append("\tProtected WithEvents " + col.ColumnName + " As System.Web.UI.WebControls.TextBox" + nl);
						break;
					default:
						sbBody.Append("\tProtected WithEvents " + col.ColumnName + " As System.Web.UI.WebControls.TextBox" + nl);
						break;
				}
			}

<xsl:apply-templates select="entity" mode="Private"/>
        Private __Ma_Nuoc As String
        Private __Ma_HTS As String
        
        
        Private _sUrl As String

#End Region

#Region "Event Handlers"
        Private Sub Page_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
            Try
                _sUrl = CType(Settings("WebServiceUrl"), String)
                If _sUrl = "" Then
                    _sUrl = Config.GetSetting("WebServiceRoot") & "SHTS_WS.asmx"
                End If

				<xsl:apply-templates select="entity" mode="SetPrivate"/>

                If Not (Request.Params("Ma_Nuoc") Is Nothing) Then
                    __Ma_Nuoc = Request.Params("Ma_Nuoc")
                Else
                    __Ma_Nuoc = ""
                End If
                If Not (Request.Params("Ma_HTS") Is Nothing) Then
                    __Ma_HTS = Request.Params("Ma_HTS")
                Else
                    __Ma_HTS = ""
                End If

                If Not Page.IsPostBack Then
                    cmdDelete.Attributes.Add("onClick", "javascript:return confirm('" & Localization.GetString("DeleteItem") & "');")
                    If __Ma_Nuoc <> "" And __Ma_HTS <> "" Then
                        Dim kpi As New SHTS_BOWS(_sUrl)
                        Dim bibi As SHTS_Info
                        bibi = kpi.SelectItem(__Ma_HTS, __Ma_Nuoc)
                        If Not bibi Is Nothing Then
                            'Load data
                            Ma_HTS.Text = bibi.Ma_HTS
                            Ma_Nuoc.Text = bibi.Ma_Nuoc
                            Ten_HTS.Text = bibi.Ten_HTS
                            Ma_DVT.Text = bibi.Ma_DVT
                            Ma_CAT.Text = bibi.Ma_CAT
                            Ma_HTS.Enabled = False
                            Ma_Nuoc.Enabled = False

                            cmdDelete.Visible = True
                        Else ' security violation attempt to access item not related to this Module
                            Response.Redirect(NavigateURL(), True)
                        End If
                    End If
                End If
            Catch exc As Exception
                ProcessModuleLoadException(Me, exc)
            End Try
        End Sub

        Private Sub cmdUpdate_Click(ByVal sender As Object, ByVal e As EventArgs) Handles cmdUpdate.Click
            Try
                ' Only Update if the Entered Data is Valid
                If Page.IsValid = True Then
                    Dim bibi As New SHTS_Info

                    'bind text values to object
                    bibi.Ma_HTS = __Ma_HTS
                    bibi.Ma_Nuoc = __Ma_Nuoc
                    bibi.Ten_HTS = Ten_HTS.Text
                    bibi.Ma_DVT = Ma_DVT.Text
                    bibi.Ma_CAT = Ma_CAT.Text

                    Dim kpi As New SHTS_BOWS(_sUrl)
                    If __Ma_HTS = "" Then
                        bibi.Ma_HTS = Ma_HTS.Text
                        bibi.Ma_Nuoc = Ma_Nuoc.Text
                        kpi.InsertItem(bibi)
                    Else
                        kpi.UpdateItem(bibi)
                    End If

                    ' Redirect back to the portal home page
                    Response.Redirect(NavigateURL(), True)
                End If
            Catch exc As Exception
                ProcessModuleLoadException(Me, exc)
            End Try
        End Sub

        Private Sub cmdCancel_Click(ByVal sender As Object, ByVal e As EventArgs) Handles cmdCancel.Click
            Try
                Response.Redirect(NavigateURL(), True)
            Catch exc As Exception
                ProcessModuleLoadException(Me, exc)
            End Try
        End Sub

        Private Sub cmdDelete_Click(ByVal sender As Object, ByVal e As EventArgs) Handles cmdDelete.Click
            Try
                If __Ma_HTS <> "" Then
                    Dim kpi As New SHTS_BOWS(_sUrl)
                    kpi.DeleteItem(__Ma_HTS, __Ma_Nuoc)
                    kpi = Nothing
                End If

                ' Redirect back to the portal home page
                Response.Redirect(NavigateURL(), True)
            Catch exc As Exception
                ProcessModuleLoadException(Me, exc)
            End Try
        End Sub
#End Region

#Region " Web Form Designer Generated Code "

        'This call is required by the Web Form Designer.
        <System.Diagnostics.DebuggerStepThrough()> Private Sub InitializeComponent()

        End Sub

        'NOTE: The following placeholder declaration is required by the Web Form Designer.
        'Do not delete or move it.
        Private designerPlaceholderDeclaration As System.Object

        Private Sub Page_Init(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Init
            'CODEGEN: This method call is required by the Web Form Designer
            'Do not modify it using the code editor.
            InitializeComponent()
        End Sub

#End Region

    End Class

End Namespace


</xsl:template>
</xsl:stylesheet>
