
'' =============================================
'' This class is generated by TuấnNA2
'' Author:	Nguyễn Anh Tuấn
'' Create date:	12/11/2012 12:50
'' Description:	The properties of MHS_DIEU_CHINH_MA_SO object
'' Revise History:	
'' =============================================

Public class MHS_DIEU_CHINH_MA_SO_Info
	Inherits InfoBase
	
						Private _M_ID as integer
						Private _SO_TK as integer
						Private _MA_LH as string
						Private _MA_HQ as string
						Private _NAM_DK as integer
						Private _ID_HANG as integer
						Private _NGAY_DK as date
						Private _C_ID as Nullable(Of string)
					
	public sub New()

	End sub
	
						Public Property M_ID() as integer
						Get
							Return _M_ID
						End Get
						Set(ByVal Value as integer)
							_M_ID = Value
						End Set
						End Property
					
						Public Property SO_TK() as integer
						Get
							Return _SO_TK
						End Get
						Set(ByVal Value as integer)
							_SO_TK = Value
						End Set
						End Property
					
						Public Property MA_LH() as string
						Get
							Return _MA_LH
						End Get
						Set(ByVal Value as string)
							_MA_LH = Value
						End Set
						End Property
					
						Public Property MA_HQ() as string
						Get
							Return _MA_HQ
						End Get
						Set(ByVal Value as string)
							_MA_HQ = Value
						End Set
						End Property
					
						Public Property NAM_DK() as integer
						Get
							Return _NAM_DK
						End Get
						Set(ByVal Value as integer)
							_NAM_DK = Value
						End Set
						End Property
					
						Public Property ID_HANG() as integer
						Get
							Return _ID_HANG
						End Get
						Set(ByVal Value as integer)
							_ID_HANG = Value
						End Set
						End Property
					
						Public Property NGAY_DK() as date
						Get
							Return _NGAY_DK
						End Get
						Set(ByVal Value as date)
							_NGAY_DK = Value
						End Set
						End Property
											
						Public Property C_ID() as Nullable(Of string)
						Get
							Return _C_ID
						End Get
						Set(ByVal Value as Nullable(Of string))
							_C_ID = Value
						End Set
						End Property
					
End Class

